---
openapi: 3.0.0
info:
  title: Chord Weaver API
  description: Chord Weaver API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/taylor-cox/chord-weaver/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://localhost:3000/
  description: Local Server
paths: {}
components:
  schemas:
    Schema:
      type: object
      properties:
        id:
          type: integer
          format: int64
