binop_separator = "Back"
blank_lines_upper_bound = 2
brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
empty_item_single_line = true
enum_discrim_align_threshold = 30
fn_params_layout = "Tall"
fn_single_line = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
max_width = 80
imports_granularity = "Module"
newline_style = "Native"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 30
struct_lit_single_line = false
struct_lit_width = 0
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Off"
where_single_line = true
wrap_comments = true